language: python
python: 2.7
cache: pypi

install:
  - echo "no indepedencies"

script:
  - python2 -m pytest -vvv tests/

branches:
  only:
  - master

after_success:
 - bash <(curl -s https://codecov.io/bash)

